---
title: "Module 7"
author: "Erin Anderson"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## CHALLENGE 1
```{r gemoetric mean, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
x <- c(1,2,3,4,5,6,7,8,9,10,100,1000)
geometric_mean <- exp(mean(log(x)))
geometric_mean
```
## CHALLENGE 2
```{r sum of squares, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
sum_of_squares <- function(x) {sum((x - mean(x))^2)}
sum_of_squares(x)
```
## CHALLENGE 3
```{r variance, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
sample_variance <- function(x) {sum((x - mean(x))^2)/(length(x) - 1)}
sample_variance(x)
```
## PLOTTING
```{r plotting, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
plot(c(0, 50), c(0, 15), type = "n", xlab = "Sample size", ylab = "Variance")
for (n in seq(5, 50, 5)) # samples of 5-50 by 5.
{
    for (i in 1:50) #50 replicates
    {
        x <- rnorm(n, mean = 10, sd = 2)
        points(n, var(x))
    }
}
```
## VARIANCE AND STANDARD DEVIATION
```{r variance, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pop_v <- function(x) {   sum((x - mean(x))^2)/(length(x))
}
pop_v(x)
op_sd <- function(x) {
     sqrt(pop_v(x))
}
pop_v(x)

#or
sample_sd <- function(x) {
    sqrt(sample_v(x))
}
sample_sd(x)
```
## CHALLENGE 4
```{r standard error, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
SE2 <- function(x) {
    sqrt(var(x)/length(x))
}
SE2(x)
# or
SE1 <- function(x) {
    sqrt(sample_v(x)/length(x))
}
SE1(x)
#or
library(sciplot)
se(x)
```
